# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3311:3306
    security_opt:
      - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - 8092:8080
