POST http://wcasg.test/api/audit/create
Content-Type: application/json

{
  "url": "example.com"
}
###

POST https://dashboard.widget.wcasg.solarix.dev/api/audit/create
Content-Type: application/json

{
  "url": "example.com"
}
###

POST http://wcasg.test/api/audit/create
Content-Type: application/x-www-form-urlencoded

url=google.com

###
