POST http://wcasg.test/api/audit/create
Content-Type: application/json

{
  "url": "example.com"
}
###

POST http://178.128.7.36/api/audit/create
Content-Type: application/json

{
  "url": "example.com"
}
###

POST http://wcasg.test/api/audit/create
Content-Type: application/x-www-form-urlencoded

url=google.com

###
